name: BiTV Daily Update

on:
  schedule:
    - cron: '0 16,22,4,10 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run scraping script
      run: python .github/workflows/BiTV.py

    - name: GetTime
      id: date
      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_OUTPUT

    - name: Update README.md
      run: |
        echo -e "# BiTV 自动更新\n\n### 更新于 ${{ steps.date.outputs.GET_TIME }}\n\n### 包含格式:\n- [M3U播放列表](BiTV.m3u)\n- [TXT播放列表](BiTV.txt)" > README.md

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add BiTV.m3u BiTV.txt README.md
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "自动更新：${{ steps.date.outputs.GET_TIME }}"
          git push origin HEAD:main
        fi
