name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'  # 每天在凌晨1点、7点、13点、19点运行

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史
    
    - name: Update EPG Files
      id: update
      run: |
        # 使用临时文件避免部分下载
        temp_file=$(mktemp)
        
        # EPG源列表，按优先级排序
        epg_urls=(
          "https://epg.112114.xyz/pp.xml"  # 第一优先级，最全面
          "http://e.erw.cc/e.xml"          # 第二优先级
        )
        
        epg_source=""
        old_epg_hash=""
        
        # 计算现有epg.xml的完整文件哈希（如果存在）
        if [ -f epg.xml ]; then
          old_epg_hash=$(sha256sum epg.xml | cut -d' ' -f1)
          echo "现有epg.xml文件哈希: $old_epg_hash"
        else
          echo "epg.xml文件不存在，将尝试所有EPG源"
        fi
        
        # 按优先级尝试下载EPG文件
        for url in "${epg_urls[@]}"; do
          echo "正在从 $url 下载EPG文件..."
          wget -nv -O "$temp_file" "$url"
          
          if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
            # 计算下载文件的哈希值
            new_epg_hash=$(sha256sum "$temp_file" | cut -d' ' -f1)
            echo "来自'$url'文件哈希值: $new_epg_hash"
            
            # 比较文件哈希值
            if [ "$old_epg_hash" != "$new_epg_hash" ]; then
              # 使用来自此源的EPG文件
              epg_source="$url"
              mv "$temp_file" epg.xml
              echo "changed=true" >> $GITHUB_ENV
              echo "使用$epg_source的EPG更新"
              break
            else
              echo "从'$url'下载的文件与现有文件无差异"
            fi
          else
            echo "::error::下载的文件无效或为空"
          fi
          
          rm -f "$temp_file"
        done
        

    - name: 提交更改
      if: ${{ env.changed == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "EPG更新: $(date +'%Y-%m-%d %H:%M:%S')"
    
    - name: Push changes
      if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # 修改：使用secrets.GITHUB_TOKEN作为token
        repository: ${{ github.repository }}  # 添加：指定仓库信息，可选但推荐
        branch: ${{ github.ref_name }}  # 添加：指定分支，可选但推荐
