name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Update EPG Files
      id: update
      run: |
        # 设置选项：errexit 和 pipefail
        set -o errexit
        set -o pipefail
        
        # 定义所有 EPG 源，按优先级排序
        epg_urls=(
          "https://epg.112114.xyz/pp.xml"  # 第一优先级
          "http://epg.51zmt.top:8000/e.xml"  # 第二优先级
          "http://e.erw.cc/e.xml"           # 第三优先级
        )
        
        changed=false
        # 检查 epg.xml 是否已存在
        if [ ! -f epg.xml ]; then
          # 如果文件不存在，初始化为空文件以避免后续 cmp 报错
          touch epg.xml
          changed=true
          echo "epg.xml 文件不存在，初始化新文件。"
        fi
        
        echo "开始检查 EPG 源..."
        echo "可用的 EPG 源数量: ${#epg_urls[@]}"
        
        # 使用临时文件
        temp_file=$(mktemp)
        new_source_url=""
        new_file_downloaded=false

        for url in "${epg_urls[@]}"; do
          echo "正在从 $url 下载 EPG 数据..."
          
          # 下载文件
          if wget -nv -O "$temp_file" "$url"; then
            # 检查文件是否有效
            if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
              echo "从 '$url' 下载成功，内容："
              head -n 10 "$temp_file"  # 显示文件前10行作为确认
              
              # 检查与本地文件的差异
              if ! cmp -s "$temp_file" epg.xml; then
                new_source_url="$url"
                new_file_downloaded=true
                
                # 移动新文件
                echo "EPG 文件内容已更改，使用从 '$url' 下载的新文件。"
                mv "$temp_file" epg.xml
                changed=true
                echo "EPG 文件已更新，来自源: $url"
                break  # 找到更新后可停止检查
              else
                echo "从 '$url' 下载的文件与本地 epg.xml 内容相同，跳过更新。"
              fi
            else
              echo "::error::从 '$url' 下载的文件无效或为空，请检查 URL 或文件内容。"
            fi
          else
            echo "::error::无法从 '$url' 下载 EPG 文件。"
          fi
        done

        if [ "$changed" = "true" ]; then
          echo "EPG 文件成功更新，来源为: $new_source_url"
          echo "准备提交更改..."
        else
          echo "未检测到 EPG 文件变化，跳过提交步骤。"
        fi

        # 清理临时文件
        rm -f "$temp_file"

        # 将 changed 变量输出为环境变量，供后续步骤使用
        echo "changed=$changed" >> $GITHUB_ENV

    - name: Commit changes
      if: ${{ env.changed == 'true' }}
      run: |
        # 安全配置git环境
        git config --global user.email "github-actions@noreply.com"
        git config --global user.name "GitHub Action Bot"
        
        # 验证 epg.xml 是否确实变化
        if [ -f epg.xml ] && cmp -n epg.xml .github/epg-latest.xml || [ ! -f .github/epg-latest.xml ]; then
          echo "准备提交 epg.xml 更改"
          git add epg.xml
          
          # 设置提交消息
          current_date="$((TZ=${env.TZ} date +'%Y-%m-%d %H:%M:%S %Z'))"
          commit_message="EPG更新: $current_date"
          
          git commit -m "$commit_message"
          
          # 使用 API 密钥推送更改
          if [ "$GITHUB_TOKEN" != "" ]; then
            echo "使用 GITHUB_TOKEN 推送更改"
            git push origin HEAD --force-with-lease || true
          else
            echo "警告：GITHUB_TOKEN 未设置，跳过硬推"
          fi
        else
          echo "epg.xml 未更改，无需提交"
        fi

    - name: Manual push using API
      if: ${{ env.changed == 'true' }}
      uses: stuartlewis/manual-action@v1.0.0
      with:
        command: |
          # 获取最新文件信息
          echo "推送 EPG 更新: $(date -R)"
          
          # 确认 epg.xml 已更新
          if ! cmp -s epg.xml .github/epg-latest.xml || [ ! -f .github/epg-latest.xml ]; then
            echo "EPG 文件已变化，准备推送"
            
            # 设置 GITHUB_TOKEN 环境变量
            if [ "$GITHUB_TOKEN" = "" ]; then
              echo "错误：缺少 GITHUB_TOKEN 环境变量，请确保已设置！"
              exit 1
            fi
            
            # 存储当前目录
            working_dir=$(pwd)
            
            # 检查 token 是否有效
            if curl -Is --header "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/user > /dev/null; then
              echo "GITHUB_TOKEN 有效，开始提交更改"
              
              # 执行 git 提交和推送
              cd "$working_dir"
              git config user.email "github-actions@noreply.com"
              git config user.name "GitHub Action Bot"
              git add epg.xml
              git commit -m "EPG更新: $(date -R)" -m '自动更新 EPG 数据' || exit 0
              
              # 安全推送更改
              git push origin HEAD --force-with-lease
            else
              echo "错误：GITHUB_TOKEN 失效，请在仓库设置中更新！"
            fi
          else
            echo "epg.xml 文件未变化，跳过推送"
          exit 0
          fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
