name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Update EPG Files with Checksum
      id: update
      run: |
        # 使用临时文件避免部分下载
        temp_file=$(mktemp)
        epg_file="epg.xml"
        prev_checksum=$(git show HEAD:epg.xml | md5sum | cut -d ' ' -f 1 || echo "N/A")
        
        # 文件来源列表，包括新添加的两个
        sources=(
          "https://epg.112114.xyz/pp.xml"
          "http://epg.51zmt.top:8000/e.xml"  # 注意：原URL可能有误，请确认正确域名或路径
          "http://e.erw.cc/e.xml"
        )
        
        changed=false
        
        # 遍历并下载各个数据源
        for source in "${sources[@]}"; do
          echo "Downloading $source..." >&2
         wget -nv -O "$temp_file" "$source"
          
          # 检查文件是否有效
          if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
            current_checksum=$(md5sum "$temp_file" | cut -d ' ' -f 1)
            if [ "$prev_checksum" != "$current_checksum" ] || [ "$prev_checksum" == "N/A" ]; then
              echo "MD5 checksum changed. Previous: $prev_checksum, Current: $current_checksum" >&2
              mv "$temp_file" "$epg_file"
              changed=true
            else
              echo "MD5 checksum matches existing file. No update needed." >&2
              rm -f "$temp_file"
            fi
          else
            echo "::error::无效来源: $source，下载失败或为空" >&2
            rm -f "$temp_file"
            exit 1
          fi
        done
        
        # 更新上一次下载的MD5值
        current_md5=$(md5sum "$epg_file" | cut -d ' ' -f 1)
        echo "Last MD5 sum: $current_md5" >&2
        echo "last_md5=$current_md5" >> $GITHUB_ENV

    - name: Commit and Push Changes
      if: ${{ env.changed == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add $epg_file
        git commit -m "EPG更新: $(date '+%Y-%m-%d %H:%M:%S' | fromdate "Asia/Shanghai")"
        echo "File updated and committed." >&2

    - name: Push changes
      if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false

    - name: Display current EPG file
      if: ${{ always() }}
      run: |
        head -n 20 $epg_file || echo "epg.xml is empty or unavailable"
