name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Update EPG Files
      id: update
      run: |
        # 使用临时文件避免部分下载
        temp_file=$(mktemp)
        
        # 避免重复下载相同的文件源
        sources=(
          "https://epg.112114.xyz/pp.xml"
          "http://e.erw.cc/e.xml"
          "http://epg.51zmt.top:8000/e.xml"
        )
        
        changed=false
        
        # 遍历并下载各个数据源（跳过重复项）
        for source in "${sources[@]}"; do
          wget -nv -O "$temp_file" "$source"
          
          # 检查文件是否有效
          if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
            if ! cmp -s "$temp_file" epg.xml; then
              mv "$temp_file" epg.xml
              echo "changed=true" >> $GITHUB_ENV
              changed=true
            else
              rm -f "$temp_file"
            fi
          else
            echo "::error::下载的文件无效或为空 (source=$source)"
            rm -f "$temp_file"
          fi
        done
        
        # 如果有变化，立即提交而非等到最后
        if [ "$changed" = "true" ]; then
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add epg.xml
          git commit -m "EPG更新: $(date +'%Y-%m-%d %H:%M:%S')"
        fi

    - name: Push changes
      if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false
