name: EPG Update
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1,7,13,19 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Update EPG Files
      id: update
      run: |
        # 设置选项：errexit 和 pipefail
        set -o errexit
        set -o pipefail
        # 保存当前目录并切换到 /tmp 临时目录
        cd /tmp
        # 定义要下载的 URL 列表
        urls=(
          "https://epg.112114.xyz/pp.xml"
          "http://epg.51zmt.top:8000/e.xml"
          "http://e.erw.cc/e.xml"
        )
        changed=false
        # 检查 epg.xml 是否已存在
        if [ ! -f epg.xml ]; then
          # 如果文件不存在，初始化为空文件以避免后续 cmp 报错
          touch epg.xml
          changed=true
        fi
        
        temp_file=$(mktemp)

        for url in "${urls[@]}"; do
          echo "正在从 $url 下载 EPG 数据..."
          wget -nv -O "$temp_file" "$url"

          # 检查文件是否有效
          if [ -s "$temp_file" ] && grep -q '<?xml' "$temp_file"; then
            # 比较与本地 epg.xml 文件
            if ! cmp -s "$temp_file" "../epg.xml"; then
              echo "EPG 文件内容已更改，使用从 '$url' 下载的新文件。"
              mv "$temp_file" "../epg.xml"
              changed=true
              # 找到变化后可以退出循环，避免不必要下载
              break
            else
              echo "从 '$url' 下载的文件与本地 epg.xml 内容相同，跳过更新。"
              rm -f "$temp_file"
              continue
            fi
          else
            echo "::error::从 '$url' 下载的文件无效或为空，请检查 URL 或文件内容。"
            rm -f "$temp_file"
            continue
          fi
        done

        if [ "$changed" = "true" ]; then
          echo "EPG 文件成功更新，设置 changed=true。"
        else
          echo "未检测到任何 EPG 文件变化，设置 changed=false。"
          changed="false"
        fi

        # 确保文件权限正确
        chmod --chmod=+r+wX,u+rwx,go+r "epg.xml"
        echo "::set-output name=epg_status::$changed"

        # 将 changed 变量输出为环境变量，供后续步骤使用
        echo "changed=$changed" >> $GITHUB_ENV

    - name: 提交更改
      if: ${{ env.changed == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git commit -m "EPG更新: $(date -R)"  # 添加 --date=local 选项，如果您的系统不支持 -R，可以替换为 $(date --rfc=original)

    - name: Push changes
      if: ${{ env.changed == 'true' }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false

    - name: 输出更改状态
      if: ${{ always() }}
      run: |
        echo "EPG 更新状态：$changed"
