name: IPTV Keep Daily Update

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 支持手动触发
  
env:
  TZ: Asia/Shanghai

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run scraping script
      run: python .github/workflows/iptv_keep.py

    - name: Verify file generation
      run: |
        if [ ! -f "Keep_iTV.m3u" ]; then
          echo "##[error]Keep_iTV.m3u 文件未生成！"
          exit 1
        fi
        if [ ! -f "Keep_iTV.txt" ]; then
          echo "##[error]Keep_iTV.txt 文件未生成！"
          exit 1
        fi

    - name: GetTime
      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Update README.md with run time and file links
      run: |
        echo -e "# IPTV 自动更新\n\n### 更新于 ${{ steps.date.outputs.date }}\n\n### 包含格式:\n- [M3U播放列表](Internet_iTV.m3u)（Internet_iTV.M3U）\n- [TXT播放列表](Internet_iTV.txt)（Internet_iTV.TXT）\n- [M3U播放列表](Keep_iTV.m3u)（Keep_iTV.M3U）\n- [TXT播放列表](Keep_iTV.txt)（Keep_iTV.TXT）" > README.md

    - name: Commit changes
      env:
        REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin $REPO_URL
        
        git pull origin main
        
        # 确保文件存在再添加
        [ -f "README.md" ] && git add README.md
        [ -f "Keep_iTV.m3u" ] && git add Keep_iTV.m3u
        [ -f "Keep_iTV.txt" ] && git add Keep_iTV.txt
        
        if git diff-index --quiet HEAD --; then
          echo "没有变更需要提交"
        else
          git commit -am "自动更新：${GET_TIME}"
          git push origin HEAD:main
        fi
