name: IPTV Daily Update

on:
  schedule:
    - cron: '0 */4 * * *'  
  workflow_dispatch: 
  
env:
  TZ: Asia/Shanghai

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install aiohttp

    - name: Run scraping script
      run: python .github/workflows/iptv.py

    - name: GetTime
      id: get-time
      run: echo "GET_TIME=$(date +'%Y-%m-%d %H:%M:%S CST')" >> $GITHUB_ENV

    - name: Generate README.md
      run: |
        echo -e "# iTV 自动更新\n\n### 更新于 $GET_TIME\n\n### 包含格式:\n- [M3U播放列表](Internet_iTV.m3u)\n- [TXT频道列表](Internet_iTV.txt)" > README.md

    - name: Commit changes
      env:
        REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin $REPO_URL
        
        # 添加实际存在的文件
        git add README.md
        git add Internet_iTV.m3u
        git add Internet_iTV.txt
        
        git commit -am "自动更新：$GET_TIME"
        git push origin main
